### ISSUE TITLE
dj_102.rpy:0070 选择走过桥则学妹支线消失了

### ISSUE THREAD

**Issue by lian16thu** [Big-Cherry/album#13]
选择”走过桥“那个选项，则学妹支线消失了，直接到早上赶车了。可以改一下这个选项的跳转，改到label .s13room，直接回民宿房间准备睡觉

**Comment by WentianBu** [comment]
已经根据学妹选项分别跳转到dj_girl.gs01room或者dj_102.s13room，进入蜘蛛剧情。
Fixed.
