### ISSUE TITLE
Alpha版问题汇总（图像类）

### ISSUE THREAD

**Issue by lian16thu** [Big-Cherry/album#21]
dj_start.rpy:
0093：我可以表情包
dy_102.rpy:
0063：小萝卜没有立绘
dj_105.rpy
0463：北京图没有换横版
dj_endings.rpy
密云结局可以加个密云篇的预告海报（只有到这个解决才算通关？）
dj_girl.rpy
学妹篇没有出现蜘蛛？？

**Comment by WentianBu** [comment]
dj_105.rpy:0463:
横版图已修复。

**Comment by WentianBu** [comment]
小萝卜、小天已添加立绘。

**Comment by WentianBu** [comment]
表情包已添加。

**Comment by WentianBu** [comment]
剩余问题已迁移到#26
