### ISSUE TITLE
Alpha版问题汇总（配乐类）

### ISSUE THREAD

**Issue by lian16thu** [Big-Cherry/album#22]
dy_102.rpy:
0136：百度地图“到达目标地”声音
0153：东极岛之歌可以长一点，一直延续到0196接到淘宝老板电话
0172：音乐在这里很奇怪，可以去掉
dy_103.rpy
0753：配乐消失了，可以从0758开始再加上
0132：之后可以使用东极岛之歌做配乐吧，平凡之路留到去海神庙路上用（从0163开始）
0256：可以把有原唱的版本加上
0417：怎么配乐没了？我觉得一直续到跳海挺好的
0454：没有铃铛声！到0467铃铛声停止
0467：背景音没有了
0533：高德地图音效
dj_105.rpy
0023：没有配乐了，之前那个诡异配乐可以一直延续到0037

**Comment by WentianBu** [comment]
Fixed.
