### ISSUE TITLE
Alpha版问题汇总（文字类）

### ISSUE THREAD

**Issue by lian16thu** [Big-Cherry/album#23]
dj_start.rpy:
0081：雷永宁实名了
0108：万千百惠改成万千儿
0139：万千百惠改成万千儿
dy_102.rpy:
0032：三个选项，“硬卧到宁波”、“在宁波中转”有点冲突啊，不如改成：”武汉-宁波-舟山”、“北京-宁波-舟山”、“南京-绍兴-舟山”
0188：卜文添改成小天（这一片小萝卜都改成小天）
0251：这附近都换乘小天小茶，出现了卜文添实名
dy_103.rpy
0349：谭康威出现了实名（之后实名问题不在单独列出，直接用查询功能吧）
0546：密云之旅改成密云篇
0559：邱凌岳实名了
dj_105.rpy
0442：东极之旅改成东极篇
dj_endings.rpy
0099：厕所门槛->厕所门口
密云结局可以加个密云篇的预告海报

**Comment by WentianBu** [comment]
剩余问题：

- [x] 雷永宁、郑瑜坤、邱凌岳实名；
- [x] 小茶设定是南京，与修改后的选项不符；
- [x] 预告海报问题作为图像问题 #21 等待之后添加。

**Comment by WentianBu** [comment]
All fixed.
