### ISSUE TITLE
Alpha版问题汇总（剧情类）

### ISSUE THREAD

**Issue by lian16thu** [Big-Cherry/album#24]
剧情逻辑上基本没问题了
几个想法
1、爱情保卫战阈值调低到40
2、学妹线最后不出现敦煌值测评、可以给一个好感度测评
3、各项结局应该话再多一点，比如给个什么成就体系之类的，这个需要在斟酌，算是beta版的主要修改吧
4、是否考虑只有火车结局才是正统结束？毕竟连到密云篇，想办法增强一点在其他解决的存在感

**Comment by WentianBu** [comment]
移除了结局02、03，并引导到主线。

**Comment by WentianBu** [comment]
爱情保卫战阈值已经调低到40。
学妹线最后给出好感度测评。

**Comment by WentianBu** [comment]
剩余问题已迁移到#26
