### ISSUE TITLE
Beta版问题汇总

### ISSUE THREAD

**Issue by WentianBu** [Big-Cherry/album#28]
- [x] 选择带学妹的话引入小茶
- [x] 结局1移除预告海报，只保留其他线路提示
- [x] 不上岛的相关逻辑BUG
- [x] 更换主页图（记->纪）
- [x] 检查标点符号问题（句尾逗号、没有标点符号等）
- [x] 结尾影片改字重新渲染
- [x] 末尾密云预告海报淡出问题
- [x] 增补立绘

**Comment by lian16thu** [comment]
dj_girl.rpy:0168
直接就到早上闹铃响了，可以补一句，“小茶一直没回复你，于是你只好睡觉了”

**Comment by lian16thu** [comment]
出发前补充一句“那我也要带个学妹叫小茶，是个可爱的女孩子”，或者补充一些跟她私聊的情节

主线剧情补充浴室唱歌剧情，唱歌的时候听到小茶的尖叫，出浴室之后蜘蛛照常出现

末尾密云预告海报目前是自动淡出，改成点一下再淡出

按”快读“按钮之后出现了崩溃bug

**Comment by lian16thu** [comment]
dj_102.rpy:0235
如果选择“鸟不拉屎村”，会直接跳转到码头，没有BGM（BGM可能是在民宿早上加的，这样跳过了BGM的启动）

**Comment by lian16thu** [comment]
诺诺新增捏脸：蛋蛋淫淫壮壮有容小老弟邱
